### ISSUE TITLE
How does Mapwarper functionality compare with Geoferencer Version 4 which Kloan launched this week with Rumsey?

### ISSUE THREAD

**Issue by Addaci** [timwaters/mapwarper#110]

**Comment by timwaters** [comment]
What are the functions of the Georeferencer v4?

One difference is that mapwarper is free and open source, and mapwarper.net allows individuals to upload things on their own.

**Comment by Addaci** [comment]
I will be seeing Georeferencer Version 4 for the first time this coming weekend.  Petr Pridal, CEO of Klokan, has given me a high level description of Georeferencer 4 and one key feature appeared to be instant rewarping with every incremental anchor point (though I may not have understood this correctly).david Rumsey is due to launch V4 this week, though I notice that there is no signof it yet on the Rumsey website: http://www.davidrumsey.com/view/georeferencer

**Comment by timwaters** [comment]
thanks!
