### ISSUE TITLE
Do you operate a version control system for Mapwarper?

### ISSUE THREAD

**Issue by Addaci** [timwaters/mapwarper#111]

**Comment by timwaters** [comment]
Git, here is the version control for the code, but I suspect you mean within the app :)

Mapwarper does records versions as an activity log for changes to maps, and points added.

I also wrote the NYPL warpers fuller implementation enabling users to rollback changes to a map to a specified version.  The NYPL Warper uses this to also monitor changes in a kind of dashboard seeing which users did what in an hour, day, week etc timeframe
