### ISSUE TITLE
Is the NYPL's version of Mapwarper different from your current implementation of Mapwarper?

### ISSUE THREAD

**Issue by Addaci** [timwaters/mapwarper#112]

**Comment by timwaters** [comment]
NYPL warper is at https://github.com/nypl-spacetime/nypl-warper

fundamentally they are the same, but:
NYPL Warper connects to the NYPL digital repository, for imports, regular updates etc 
NYPL Warper uses the NYPL image server for thumbnails.
NYPL Warper has different versioning, and rate limiting support.
Mapwarper.net allows anyone to upload images.
