### ISSUE TITLE
Points disappear on left side; map moves north

### ISSUE THREAD

**Issue by billwarner35** [timwaters/mapwarper#116]
http://mapwarper.net/maps/19140#Rectify_tab

Note that there are no points on the map now, and that the transformed map is shifted north by about the height of the map.

**Comment by timwaters** [comment]
This is what I see

![Uploading Screenshot_2017-03-07_12-14-18.png…]()

**Comment by billwarner35** [comment]
Aha. Is there a recommended way to fix this so as not to lose all the points already entered?

**Comment by timwaters** [comment]
Pretty sure this was made by using the Align feature. 

http://mapwarper.net/maps/19094#Rectify_tab is the one with the same points, effectively.

There are 2 options when using Align - maybe the "nicer fit, trickier to edit later" option was used.

I don't think it can be easily redone. They would all of them been offset by the same amount, so one could do it manually in the control panel interface, however the points won't be over anything in particular.

I'm closing this Issue for the moment.
