### ISSUE TITLE
1 bit black and white tif files dont work

### ISSUE THREAD

**Issue by timwaters** [timwaters/mapwarper#117]
The tiff file in the zip:

gdalinfo checkbw.tif 
Driver: GTiff/GeoTIFF
Files: checkbw.tif
Size is 641, 401
Coordinate System is `'
Metadata:
  TIFFTAG_DOCUMENTNAME=/home/tim/Desktop/checkbw.tif
  TIFFTAG_IMAGEDESCRIPTION=Created with GIMP
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_XRESOLUTION=72
  TIFFTAG_YRESOLUTION=72
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
  MINISWHITE=YES
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,  401.0)
Upper Right (  641.0,    0.0)
Lower Right (  641.0,  401.0)
Center      (  320.5,  200.5)
Band 1 Block=641x64 Type=Byte, ColorInterp=Palette
  Image Structure Metadata:
    NBITS=1
  Color Table (RGB with 2 entries)
    0: 255,255,255,255
    1: 0,0,0,255

[checkbw.tif.zip](https://github.com/timwaters/mapwarper/files/828284/checkbw.tif.zip)

produces a black image

![screenshot_2017-03-08_16-44-30](https://cloud.githubusercontent.com/assets/48941/23713672/88f5ab20-041e-11e7-8dc2-5f354802120a.png)

With error: 

"Warning 1: Unable to export color table to GeoTIFF file.  Color tables can only be written to 1 band or 2 bands Byte or UInt16 GeoTIFF files.\n

Note that an imagemagick convert:

convert checkbw.tif -type TrueColor checkbwtc.tif

also gives a black image

![screenshot_2017-03-08_16-46-39](https://cloud.githubusercontent.com/assets/48941/23713768/dafbae10-041e-11e7-9620-5952f3210934.png)

**Comment by IrlJidel** [comment]
We need to convert 1-bit to at least 8bit

```
eg imagemagick:
convert checkbw.tif -type TrueColor -depth 8  d8checkbw.tif
```
produces a viewable image

I think in gdal_translate  you have to use -ot Byte when writing the bands

**Comment by timwaters** [comment]
-expand rgb appears to work
