### ISSUE TITLE
Export (for JOSM OpenStreetMap Editor ) error

### ISSUE THREAD

**Issue by Bobo445** [timwaters/mapwarper#126]
"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

This window appeared when I clicked: export->WMS:(for JOSM OpenStreetMap Editor )

Can someone tell me what's going on?
Am I doing something wrong or this option is disabled/broken?

Thank you 4 your time.

**Comment by timwaters** [comment]
The link is not for viewing in a web browser, but is meant to be used within the JOSM editor

I agree, it shouldn't show the error if the user clicks it in the browser though!

**Comment by Bobo445** [comment]
So how shoud I use it, ex. "save link as", "copy address of link" or something else, because I don't know how obtain a working url for JOSM.

**Comment by xplora1a** [comment]
Perhaps the answer is to add a link "How to use this link" and link that to something like
https://josm.openstreetmap.de/wiki/Help/Preferences/Imagery
Can you make the actual link put the correct URL in the clipboard? in a similar way the github displays git: links

**Comment by Bobo445** [comment]
That's it, thanks :) This tutorial you posted in a link helped me a lot :)
