### ISSUE TITLE
load geojson or other shape file

### ISSUE THREAD

**Issue by answerquest** [timwaters/mapwarper#129]
While rectifying, enable user to load a vector polygon file, like geojson, kml, gpx etc on to the right side.
Can use something like this:
https://github.com/makinacorpus/Leaflet.FileLayer

How this would help: We may have an outer edge KML for the map image we want to warp, while the image would have the internal details. Having the file overlaid on the web map would help us pin locations a lot easier. Especially in places like rural areas of India (my use case) where openstreetmap coverage isn't sufficient yet.

Note: This could be combined with: https://github.com/timwaters/mapwarper/issues/72

**Comment by timwaters** [comment]
There is a new function to load in a reference layer from an external source (or other map) https://thinkwhere.wordpress.com/2017/04/06/rectify-new-shortcuts-and-add-layer-features-in-mapwarper-net/

ZXY ordered scheme e.g. https://example.com/osm/{z}/{x}/{y}.png

**Comment by answerquest** [comment]
Hi Tim, thanks so much for replying.
The external tiles source functionality is excellent, is coming in handy for some other use cases. But I don't know how to render a vector shape to tiles and don't think I'll be able to serve tiles this way even if I do manage to render it. It seems too much roundabout.
Let me see if I can incorporate the needed code and submit a pull request.
