### ISSUE TITLE
Mosaics nto Working

### ISSUE THREAD

**Issue by fedsanchez** [timwaters/mapwarper#138]
I am new to Map Warper.   I have uploaded several maps, which I cropped to remove the legends.  I also transformed them from jp2 to jpg, since the jp2 did not seem to work.  The files are rather large, at 150Mb-200Mb each.  I have successfully rectified many of the maps, but the last 2 rectify in 3 seconds, but really, it is not rectified.  When I try to make a mosaic, it does not seem to be working.

Here are my maps
http://mapwarper.net/users/6978/maps

The last 2 (ie 20SE191710 and 20 SW191707) cannot be rectified for some reason.  

Here are my mosaics.
http://mapwarper.net/layers/832
http://mapwarper.net/layers/840
http://mapwarper.net/layers/839

Maybe my files are too big? I am wondering what I am doing wrong.  Any help would be great.  Thanks in advance,

Fed

**Comment by timwaters** [comment]
Thanks. I received your email also. 

Closing this as it's not to do with the codebase

**Comment by fedsanchez** [comment]
Thank you so much. It was working great now!

Fed
