### ISSUE TITLE
Cropping Error on One Map in a Mosiac

### ISSUE THREAD

**Issue by billwarner35** [timwaters/mapwarper#140]
http://mapwarper.net/maps/12997#Crop_tab  This map is cropped, but doesn't show up with the cropping I applied. It seems to be "stuck" in a prior cropping.

You can see that most of the planned highway (red) is cropped, but the one area is not:
http://mapjunction.com/index.html?id=/5340

http://mapwarper.net/maps/13017#Preview_tab

It does show up cropped within Mapwarper, but when mapwarper serves up the tiles into Mapjunction, it seems that that one map is lacking the cropping

**Comment by billwarner35** [comment]
http://mapjunction.com/VIEWER/5342

If you view this you'll notice that the red highway stops abruptly. I wonder whether the tile cache on the server is not being cleared, even though the cropping has been updated. I also wonder if certain tiles are being eliminated from the cache, but not updated, causing some tiles to disappear.

Try zooming in and out. You'll see red highway go further west on some layers.

![screen shot 2017-10-24 at 6 57 54 pm](https://user-images.githubusercontent.com/19232455/31972284-d99098cc-b8ed-11e7-9ed7-581407281b6b.jpg)

**Comment by billwarner35** [comment]
http://mapjunction.com/index.html?id=/5340

Notice that the the map 13017 is not cropped tightly. This the map that goes through cambridge.

![screen shot 2017-10-24 at 7 03 03 pm](https://user-images.githubusercontent.com/19232455/31972375-638d0e02-b8ee-11e7-8b6a-6712abcc7ff0.jpg)

**Comment by timwaters** [comment]
I think the issue here is that you have copies of the same map in the mosaic, leading to overlapping images

http://mapwarper.net/maps/13015#Crop_tab

**Comment by timwaters** [comment]
![screenshot_2017-10-26_12-29-54](https://user-images.githubusercontent.com/48941/32050619-6460b3e0-ba49-11e7-92e1-1f52902bac6b.png)
