### ISSUE TITLE
Unable to send confirm mail in Vagrant 

### ISSUE THREAD

**Issue by lannio** [timwaters/mapwarper#141]
Hello
After I deploy the system via vagrant in ubuntu16.04,when I create account,the system do not send a confirm email,how to fix it?
Did I miss some settings? I only use the vagrant,but not use the other settings in "README.md" like "Database initialization" .
So when I deploy the system via vagrant,what else do I have to do to make the system work?
Thank you!

**Comment by kamataryo** [comment]
Hi, maybe this topic is related. hope to be helpful.
https://github.com/timwaters/mapwarper/pull/103

**Comment by timwaters** [comment]
Yes, Vagrant is designed for local only development and not for exposure to the public, so the ability to send mails wasn't added by default.  To set up a user, you can add one via the console, https://github.com/timwaters/mapwarper#database-initialization

Or you can monitor the development.log and see the mail and links printed out there.

Tim
