### ISSUE TITLE
500 Errors when requesting tiles from mapwarper.net

### ISSUE THREAD

**Issue by jamiefolsom** [timwaters/mapwarper#144]
Not for all maps, but for this one in particular, mapwarper.net consistently returns 500 errors to all requests for map tiles using the OSM scheme: `http://mapwarper.net/maps/9175/`

I am using this template: `http://mapwarper.net/maps/tile/9175/{z}/{x}/{y}.png`

For all tile requests, I see something like this in the chrome network console:

```
Request URL:http://mapwarper.net/maps/tile/9175/15/17520/12176.png
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:138.201.16.203:80
Referrer Policy:no-referrer-when-downgrade
```

Here's the map page: http://hofstra.github.io/itinerary/melville-in-rome/

**Comment by timwaters** [comment]
Hello, Thanks for the issue. 

You should ensure that the map can be rectified. Some older maps may need to be re-rectified as there was an issue with lack of space on the server.  

I was able to rectify https://mapwarper.net/maps/9175#Rectify_tab and the tiles loaded okay

Additionally, if you could email me the ID's of these maps, I can make sure they are more protected from future pruning.

**Comment by jamiefolsom** [comment]
Thanks a million, @timwaters. Your hosting others' maps is greatly appreciated!
