### ISSUE TITLE
Picture not uploading

### ISSUE THREAD

**Issue by bgillespie1024** [timwaters/mapwarper#145]
Hi, I am trying to map warp a high-resolution areal photo.  The issue is that every time I upload it I can't view the picture.  Instead of seeing the picture I just get a pink screen with a broken image notification in the upper left-hand corner.  Also, when I look at the label for the map I can see the image just fine, it is only when I am trying to rectify it that I cannot see it.  Along with this when I do rectify it when I got to preview it says it is not rectified.
Do I need to upload the photo a different way than just a jpg or can I just not use it because it is a high-resolution photo?
Thank you.

**Comment by timwaters** [comment]
If it's a jpeg2000 you might try changing to a normal jpg, or a PNG.
