### ISSUE TITLE
WMS not working in ArcGIS online or QGIS 

### ISSUE THREAD

**Issue by burnt-sienna** [timwaters/mapwarper#149]
The following WMS link:
http://mapwarper.net/mosaics/wms/101?request=GetCapabilities&service=WMS&version=1.1.1 
does not work at all in ArcGIS online - it fails to add as a layer.
In QGIS - a connection is made but errors are enountered on the download.
Adding a map as a Tile Service in ArcGIS online appears to work as layers are retrieved but nothing is displayed e.g using https://mapwarper.net/maps/tile/3124/{z}/{x}/{y}.png
Any ideas as to why this is and can it be fixed?
Kind Regards

**Comment by timwaters** [comment]
I think its related to #128

**Comment by burnt-sienna** [comment]
Thanks,
The tile service actually works - my error - /{level}/{col}/{row}.png needed as input instead of /{z}/{x}/{y}.png 
However, still not sure what to do with the WMS link.

**Comment by timwaters** [comment]
This should be fixed now. Not seeing any errors on the server, and its working fine in QGIS. I tried it on arcgis explorer too (but dont have arcmap).

It now will send the thumbnail of a map as the legend!

![screenshot_2018-02-27_14-39-49](https://user-images.githubusercontent.com/48941/36739873-eddb545e-1bd8-11e8-813c-0718eb255cd1.png)
