### ISSUE TITLE
api doc link on help.html is wrong

### ISSUE THREAD

**Issue by timwaters** [timwaters/mapwarper#150]
The API link on the Subject title page is coming back as:

http://mapwarper.net/mapwarper.net/api/v1/

and I think you want it to be:

http://mapwarper.net/api/v1/

**Comment by timwaters** [comment]
Im pretty sure this is correct now closing

**Comment by jidanni** [comment]
Yes correct in the HTML, but there is some javascript or something still adding the junk at front.
Visit http://mapwarper.net/help and have a try.

**Comment by jidanni** [comment]
You are missing a slash still.
```
$ mech-dump --links http://mapwarper.net/help|sort|tail
http://mapwarper.net/help?locale=nl
http://mapwarper.net/layers/geosearch
http://mapwarper.net/maps
http://mapwarper.net/maps/geosearch?show_warped=1
http://mapwarper.net/maps?show_warped=1
http:/mapwarper.net/api/v1/
https://github.com/timwaters/mapwarper/issues
https://www.paypal.me/timdevelops
https://www.paypal.me/timdevelops
https://www.paypal.me/timdevelops
```
