### ISSUE TITLE
Reuse ground-control points / Command-line usage

### ISSUE THREAD

**Issue by moermann** [timwaters/mapwarper#153]
Hi Tim, 

thanks for your great app. I have successfully rectified [a map of North Sea oil & gas fields](http://mapwarper.net/maps/29901). Now I would like to use the ground-control points for warping again the same map, but stripped off all content except the gas fields.

But this map contains no references anymore, so it's impossible to locate ground-control points. So is it possible to import the ground-control points from another rectification?

If it's not possible online, can I do it offline with your ruby scripts?

**Comment by timwaters** [comment]
You can download the control points from one map and upload to another one Look for the "Control panel" 
![image](https://user-images.githubusercontent.com/48941/38731606-ee0533e8-3f12-11e8-8870-b7a9f37627ca.png)
