### ISSUE TITLE
ERROR WMS GetCapabilities url not working

### ISSUE THREAD

**Issue by miapartlow** [timwaters/mapwarper#164]
There is an error with the WMS Capabilities URL.  As an example, using rectified map with ID 34338, the WMS capabilities URL links to: https://mapwarper.net/maps/wms/34338?request=GetCapabilities&service=WMS&version=1.1.1

A black screen with a small empty bounding box appears in the center of the screen.

**Comment by timwaters** [comment]
note that deployment to mapwarper.net may be delayed

**Comment by timwaters** [comment]
should be on mapwarper.net now

**Comment by miapartlow** [comment]
Wonderful!

Mia
