### ISSUE TITLE
Add "translate and redirect" capability

### ISSUE THREAD

**Issue by jidanni** [timwaters/mapwarper#168]
Perhaps there is a use case for, not actually serving map tiles,
but just translating tile URLs. E.g, for
https://github.com/openstreetmap/iD/issues/6198

Mapwarper could get a request for a tile, and return an HTTP redirect to the translated tile.

E.g., a request comes in for
http://mapwarper.net/maps/tile/99999/{z}/{x}/{y}.jpg
and mapwarper responds with a HTTP redirect to
http://nurdsburg.barf/Tile/RSImage/Airplane/mmm/{z}/{y}/{x-1}.jpg
or whatever the user had specified in his translator template.

**Comment by timwaters** [comment]
https://github.com/timwaters/whoots  might be a better place for this?

**Comment by jidanni** [comment]
Hmm, and add [ability to even translate the [toughest coordinates](https://josm.openstreetmap.de/ticket/17618#comment:6), and ability to just generate HTTP redirects...
