### ISSUE TITLE
Incomplete response received from application while uploading image

### ISSUE THREAD

**Issue by viperet** [timwaters/mapwarper#169]
When I try to upload my aerial photo, I always get "Incomplete response received from application" error on a blank white page. Tried to upload a very small image, only 314KB.

**Comment by timwaters** [comment]
The servers run out of disk space and I'm also on vacation. I hope to get everything fixed when I return soon

**Comment by meo9979** [comment]
Same issue re-occured on 2022-09-23

Tried to delete existing maps to help but I can't either.

**Comment by timwaters** [comment]
yes, server ran out of space, very rapidly. New uploads have had to be disabled
