### ISSUE TITLE
Which is the best mapwarper repo to use?

### ISSUE THREAD

**Issue by mradamcox** [timwaters/mapwarper#171]
This seems like the main repo for the Map Warper project (because it has so many forks), but I see that the [Kartta Labs repo](https://github.com/kartta-labs/mapwarper) has more recent commits, even though it has no ticket traffic and is not a fork of this repo. Which one should I use if I want to set up a test instance of Map Warper?

**Comment by timwaters** [comment]
This is what mapwarper.net is using. kartta labs is more bespoke. The changes in that repo will be rolled into this one sooner or later.
