### ISSUE TITLE
Map Tiles returning 500 errors

### ISSUE THREAD

**Issue by circa1977** [timwaters/mapwarper#175]
An embedded map we built back in 2015/2016 is now returning 500 errors for the map tile images.

https://www.cfregisters.org/en/scholarly-resources/paris-playhouses

Is that something we should expect to be seeing?

Thanks!

**Comment by timwaters** [comment]
Have you logged into the site and made sure the map can be rectified? If you can that will probably be what's needed. Older maps outputs were deleted to free up space.
