### ISSUE TITLE
Rectified Map Not Displaying Properly in GPS App

### ISSUE THREAD

**Issue by DonpK** [timwaters/mapwarper#177]
After rectifying a map, when I compare the control points shown in the Map Warper Control Point table, the longitude and latitude of the each point matches quite well with the OSM web version. However, when I load the geotiff  version into my GPS tracking app, [Avenza Maps](https://www.avenza.com/avenza-maps/), the coordinates of the control point locations are substantially in error. 

I sent the file to Avenza and they said there are " issues with the georeferencing", not with their app.

Do you have any suggestions of how I can troubleshoot this problem? It could be a problem with the way I'm using Map Warper.

Don

**Comment by timwaters** [comment]
Hi, could you include the link to the map on mapwarper?

**Comment by DonpK** [comment]
Hi Tim,
Here is the link to the Lancaster 1831 map:  https://mapwarper.net/maps/44692

The map currently has only three control points, however, I tried earlier attempts with more points.

Thanks for your help

**Comment by timwaters** [comment]
Hmm, looks strange when warped:
![image](https://user-images.githubusercontent.com/48941/72154570-eb189300-33a8-11ea-9e69-1beb2f9efbfd.png)

I think its because of the original TIFF color-space or bands... you could try converting it to a jpeg and try again and see whats thats like

**Comment by timwaters** [comment]
looks okay now. Give it a go now with the app

**Comment by DonpK** [comment]
Thanks for your help. The map looks good now in the Avenza Maps app. Also, I realized I was making a stupid mistake. The Avenza coords are in degrees decimal minutes and the Map Warper coords are decimal degrees. Once I did the conversion, things looked much better. Did I do something wrong in the cropping procedure?
For what it's worth, here is a screenshot of the Avenza details on the map:

![Lancaster 1831 Avenza Screenshot](https://user-images.githubusercontent.com/13510364/72161563-59039100-338e-11ea-9cf7-6dd9a81ef85a.png)

**Comment by DonpK** [comment]
Tim, could you explain what I'm doing wrong when cropping the map and how to undo it? It happened again with another map:  https://mapwarper.net/maps/44895  The rectified map looked good until I tried to crop it, then it turned into a fuzzy blob.

**Comment by timwaters** [comment]
Hi Don, in this case it wasnt the crop. I deleted the cropping mask and added a basic one, sorry. 

In this case there were 3 identical control points on top of each other, so I deleted the dupes and it looks okay now

![image](https://user-images.githubusercontent.com/48941/72350135-be7cb800-36d5-11ea-8aa9-9da701fadc98.png)

I'll close the issue now :) Thanks
