### ISSUE TITLE
500 server error when requesting map tiles

### ISSUE THREAD

**Issue by puppylush** [timwaters/mapwarper#179]
on http://lostpubsofbishopscastle.co.uk/, mapping has been replaced by error messages. In the console, every request to mapwarper returns a 500 Internal server error.

**Comment by puppylush** [comment]
for example: http://mapwarper.net/maps/tile/12484/17/64443/43000.png

**Comment by timwaters** [comment]
Hi, you just need to rectify the maps again. some maps results which were not touched for (literal) years were deleted

**Comment by DonpK** [comment]
I would also be glad to contribute to Mapwarper if a PayPal option could be made available.

**Comment by timwaters** [comment]
there's only donations links provided, the system is free and not a freemium /  paid service for people to use. I think there could be a business case for making it like that, but I havent the time to start such a business.
