### ISSUE TITLE
Warn users that older maps need to be re-rectified, or may be deleted

### ISSUE THREAD

**Issue by JackDougherty** [timwaters/mapwarper#181]
I'm one of the many users who love MapWarper and greatly appreciate this wonderful tool and service. But recently I was confused when several historical maps that I had uploaded in 2015-2016 stopped working in my Leaflet maps. 

Then I discovered these closed issues, which revealed serious warnings that do NOT appear on the MapWarper.net instructions or help page, or the GitHub repo README page, about the need to re-rectify older maps, or the possibility that older maps may be deleted from the server: 

https://github.com/timwaters/mapwarper/issues/179
"Some older maps may need to be re-rectified as there was an issue with lack of space on the server.”

https://github.com/timwaters/mapwarper/issues/175 
"Hi, you just need to rectify the maps again. some maps results which were not touched for (literal) years were deleted”

https://github.com/timwaters/mapwarper/issues/144
"if you could email me the ID's of these maps, I can make sure they are labelled appropriately to protect them from future pruning."

Please update your site instructions, help page, and README to make these important warnings visible to all users. Also, if there are server costs, users like me are more likely to pay if there is a clear process to label our maps to avoid future deletions.

**Comment by ilyankou** [comment]
+1

**Comment by timwaters** [comment]
Thanks. Mapwarper.net is an instance of this software, it's free, hosted by my pocketmoney and there are no guarantees of service. Don't use it but host your own if you need a guarantee. 

There was a message on the website which lasted for a few months saying this was about to occur and after it happened how to correct it. 

Maps can simply be re-created by rectifying them again, they are not deleted. 

Emails are only used for logging in by users, there is no mailing list.

**Comment by timwaters** [comment]
I think the best thing would be to have a "Caveat Emptor" on the sign up page so that folks are aware.

**Comment by timwaters** [comment]
![image](https://user-images.githubusercontent.com/48941/76308417-a6cf4380-62c2-11ea-9a3c-0322e7d4daff.png)
