### ISSUE TITLE
Rectify using only lat-long of control points? [SOLVED]

### ISSUE THREAD

**Issue by richb-hanover** [timwaters/mapwarper#182]
I just uploaded an image (Loch Lyme Lodge) that I want to convert to tiles for the Gaia GPS application.

It appears that the current GUI is designed to allow people to indicate the point on the uploaded image (on the left) that matches a point on the OSM map on the right. That gives a lat-long value for that point, and allows mapwarper to adjust the uploaded image.

Unfortunately, most of my map is in the middle of the woods. I won't be able to find good markers on the OSM image. 

However, I happen to have lat-long for several boundary markers on the map. (Isn't modern cell phone technology wonderful?) Is there a way to enter the lat-long for the control points as I enter them? Many thanks.

**Update:** I solved my own problem. When I clicked "Control Points" on the Rectify tab, it was clear that I could enter the lat-long for each of the control points that I placed on the image. It worked astonishingly well. I exported the map as tiles, imported it into Gaia GPS, and Presto! the new image now underlies my neck of the woods. And it's astonishingly accurate. What a slick process! Thanks.

**Comment by timwaters** [comment]
click "control points"

![image](https://user-images.githubusercontent.com/48941/79117302-aa9f2b80-7d82-11ea-8983-ffbc0c29479e.png)
