### ISSUE TITLE
"Incomplete response received from application"

### ISSUE THREAD

**Issue by csoko17** [timwaters/mapwarper#188]
I am trying to upload my aerial image. I keep getting this error. I am uploading the same way as I always do. What can be done so I can upload this image?

**Comment by timwaters** [comment]
server ran out of disk space. sorry

**Comment by csoko17** [comment]
I am receiving this error when trying to upload a map. "Server is out of
disk space. Uploads have been disabled temporarily."

Anything I need to do to be able to upload it?
