### ISSUE TITLE
Error while submitting Control Point

### ISSUE THREAD

**Issue by Tom-Wild** [timwaters/mapwarper#200]
Hello,
I'd like to start by apologizing if this is not the correct forum for a question. I'm not a coder, but a user, and I've never seen this behavior.

While trying to add control points, I'm seeing the following error message:
Had trouble updating that point with the server. Try again?

I've tried using different browser over two days, and it's consistent. Is there something I've forgotten to do with Mapwarper?

Thanks

**Comment by timwaters** [comment]
Thanks. the server ran out of disk space. I'll find some space and in the meantime close this issue.
