### ISSUE TITLE
Error when changing map type on a map card in the mosaic view

### ISSUE THREAD

**Issue by timwaters** [timwaters/mapwarper#205]
There's an error when changing the map type on a map if its listed under a mosaic.
It seems like its able to change a map away from "map" but not back again.
Its possible the drop down doesnt show the correct map type too.

on a map view page, or on the map list you can change the map type with no errors.

refs #204

**Comment by rwelty1889** [comment]
here is another one of mine with the issue: https://mapwarper.net/layers/1186?page=1#Show_tab
is it possible that if i remove the map from the mosaic i can then change the type? it is currently showing "is a map" but that appears to be wrong and there does not seem to be anything i can do about it.

**Comment by timwaters** [comment]
Hi,

if you open a map individually, you can change the map type to "is map"
which I have just done.  The bug is where a user changes the type in the
list of a mosaic, but it does not exist if you open a map individually and
change it there

**Comment by rwelty1889** [comment]
that approach has not been working for me. despite my inadvertent incorrect setting (is not a map), when i open it (in firefox), it always displays "is a map" and i have no mechanism for changing it that i can see.

**Comment by timwaters** [comment]
which of the 75 maps in the mosaic has the problem?
