### ISSUE TITLE
Unable to export rectified map

### ISSUE THREAD

**Issue by elwebster** [timwaters/mapwarper#206]
Hello! I am currently experiencing an issue with exporting a rectified map (Map 16684). 12 Control points have been added, but when attempting to download a KML the file appears empty, and when attempting to download a GeoTiff it returns to the Browse Maps screen with the following issue: "File Not Found. Perhaps the map has not been rectified yet?" 

Any suggestions welcome - thanks!

**Comment by timwaters** [comment]
Hello, Thanks for the report.
Some maps that belonged to users not logged in for over a year will need to
be re-rectified (to free up server space). Have you tried this?

If it works, feel free too close this issue
