### ISSUE TITLE
Too many rectify points

### ISSUE THREAD

**Issue by mrAceT** [timwaters/mapwarper#207]
Hello,

I have over 250 points, the last ones I don't see, and can't correct!

https://mapwarper.net/maps/61172

**Comment by timwaters** [comment]
click on control points and delete them from the list

![image](https://user-images.githubusercontent.com/48941/146214158-4a7d96a5-13dc-402e-aae1-a278e083ed27.png)

**Comment by mrAceT** [comment]
Thank you for the speedy reply!

(149 seems to be the max ;) )

**Comment by mrAceT** [comment]
It appears "the 149 icon" was the last one created.. guess I'm being a bit of a fanatic :P

<img src="/assets/icons/149_red.png">

**Comment by timwaters** [comment]
Your're welcome. Now lower down in the control panel is the advanced options and with so many points you could try the Thin Plate Spine for the rectify method and see if that has a better fit.

**Comment by mrAceT** [comment]
A small idea, could you redirect the '/assets/icons/ => 404 error' to a blank icon? (via .htaccess?)

**Comment by timwaters** [comment]
Good idea. I'll make an issue for it.  #208
