### ISSUE TITLE
How to delete a map?

### ISSUE THREAD

**Issue by geomantic** [timwaters/mapwarper#212]
Prefacing this issue w/ big thanks, as MW is an awesome utility. 
It's a bit unclear how to delete a map. Is it as simple as un-favoriting the map? Or, is there an explicit 'delete' function somewhere?

**Comment by timwaters** [comment]
Thanks.

You can find a link to delete a map, under the "Edit" tab for a map

**Comment by geomantic** [comment]
Thanks for the reply. However, I don't seem to have an 'edit' tab visible. Screenshot attached (Safari browser)
<img width="1295" alt="MapWarper_tabs" src="https://user-images.githubusercontent.com/126083/156891293-36036e68-8461-4486-86f7-fe64ac998381.png">

**Comment by timwaters** [comment]
Ahh, looks like you have logged in via OSM but the map was uploaded via your email and password account? The system isn't that clever to tie in the accounts of users that way. 

Note for me: I think the only thing currently gotten via OSM is the display name, email isn't available

**Comment by geomantic** [comment]
Ah, makes sense now. Thanks again for the reply! Case closed.
