### ISSUE TITLE
Unable to download tiles after rectifying map - map appears not to have rectified

### ISSUE THREAD

**Issue by puppylush** [timwaters/mapwarper#214]
Tiles have stopped loading on http://lostpubsofbishopscastle.co.uk/, so I logged in to rectify the map and regenerate the tiles.
When I rectify the map, I see a message that says 'map rectified', but if I try to preview or download the png tiles, I see messages that tell me the map has not been rectified. 

The affected map is 12484

https://mapwarper.net/maps/tile/12484/17/64444/43002.png.

Help and advice would be gratefully received, thank you :)

**Comment by timwaters** [comment]
Hi,

thanks for the issue. The map had to be re-cropped before rectifying but
the system didn't know that it should as it's a bit simple!

It should be working now, feel free to close the issue if this solves it.

(As you logged in recently hopefully it shouldn't get caught in the next
purge!)

**Comment by puppylush** [comment]
Yay! Maps! :)

Thanks so much for the swift response. I really appreciate it.

Best,

Kate
