### ISSUE TITLE
Disappearing Maps

### ISSUE THREAD

**Issue by brewingeo** [timwaters/mapwarper#217]
Hi,  I have warped a number of not maps that I upload into Gaia gps.  They are excellent guides when hiking in the field.

For some reason, they are disappearing from my Gaia app map layers, and they are also disappearing from the list of maps I have made in MapWarper.  And oddly, one "not a map" I made and rectified, uploaded to Gaia and have used repeatedly while hiking, now can't be found in Gaia, and now only shows one data Point in MapWarper, that indicates I need to add data Points and rectify it before it can be uploaded. 

It seems that some one or some thing is removing or corrupting my maps?  Ideas?

Thanks!  George

**Comment by timwaters** [comment]
Thanks for the issue.

Could you link to a map you uploaded, or  could you email me (my address is
on https://mapwarper.net/help ) your email address or name you used to
register, and I can take a look?

If you log in to mapwarper.net you may need to re-rectify and/or re-crop
the maps before they show up again

Thanks

**Comment by brewingeo** [comment]
Hi, I am George Moncure and I login with ***@***.*** and my username is George. I have had several rectified maps disappear: One is called Deep Lake Geology (on my Gaia GPS App), probably called something similar in MapWarper but it does not even appear now in my MapWarper list. Another is Big Timber Geology that was rectified and uploaded to Gaia GPS.  For some reason now, Big Timber Geology in MapWarper shows only 1 Control Point and says I need to rectify it.  Strange. Another oddity is my rectified map Billings Geology that appears in my map list in Gaia GPS and on MapWarper, but it will not show as a layer in in Gaia GPS in Windows or iOS.  Strange. Thanks, and I have to say MapWarper is brilliant.  Very nice to have warped maps on my phone when I am hiking. George Moncure Sent from Mail for Windows From: Tim WatersSent: Sunday, July 3, 2022 8:27 AMTo: timwaters/mapwarperCc: brewingeo; AuthorSubject: Re: [timwaters/mapwarper] Disappearing Maps (Issue #217) Thanks for the issue.Could you link to a map you uploaded, or could you email me (my address ison https://mapwarper.net/help ) your email address or name you used toregister, and I can take a look?If you log in to mapwarper.net you may need to re-rectify and/or re-cropthe maps before they show up againThanks—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by timwaters** [comment]
Any user can edit and delete points from other maps, this might have happened Big Lake, although the database only shows there only being 1 control point added to this map. 

https://mapwarper.net/maps/64676#Show_tab Just add some more points and re-rectify it. 

Some maps might need to be re-rectified: e.g. 
Billings https://mapwarper.net/maps/34215#Preview_Rectified_Map_tab  which should now be working.

For the missing maps, only and admin or the person who uploaded them can delete them from the database. 

I found that a map had been uploaded with the title "Geologic map of the Deep Lake quadrangle, Park County, Wyoming" but that other user had deleted it. 

You can "favourite" a map from other users and it will appear in your list. But if the other user deletes them, it will go from your list.

You could go through your activity list (see link top right "My activity") and see if a map had been deleted.  But looking in the database, only 3 maps of yours was deleted in the past: probably when you were trying out different image formats, quality etc.

 Bridger Geology, USGS Geologic Map of Soda Springs Quad, Billings Geology

**Comment by brewingeo** [comment]
Tim, Thanks much for looking into the “disappearing maps”.  Something is odd for sure as each of the maps I referred to were made by me and each were fully rectified and uploaded to my GAIA GPS app.  And I have used them each lots as I live nearby and hike and explore at each location using those overlays on my iPhone. I would never have deleted one of my maps or delete all but one control point, so I can only guess that someone has accidentally or intentionally accessed my maps.  There are, however, some maps I do not need anymore so I will delete them and change my password while I am at it. Thanks much!  Cheers, George Sent from Mail for Windows From: Tim WatersSent: Monday, July 4, 2022 5:56 AMTo: timwaters/mapwarperCc: brewingeo; AuthorSubject: Re: [timwaters/mapwarper] Disappearing Maps (Issue #217) Any user can edit and delete points from other maps, this might have happened Big Lake, although the database only shows there only being 1 control point added to this map.https://mapwarper.net/maps/64676#Show_tab Just add some more points and re-rectify it.Some maps might need to be re-rectified: e.g.Billings https://mapwarper.net/maps/34215#Preview_Rectified_Map_tab which should now be working.For the missing maps, only and admin or the person who uploaded them can delete them from the database.I found that a map had been uploaded with the title "Geologic map of the Deep Lake quadrangle, Park County, Wyoming" but that other user had deleted it.You can "favourite" a map from other users and it will appear in your list. But if the other user deletes them, it will go from your list.You could go through your activity list (see link top right "My activity") and see if a map had been deleted. But looking in the database, only 3 maps of yours was deleted in the past: probably when you were trying out different image formats, quality etc.Bridger Geology, USGS Geologic Map of Soda Springs Quad, Billings Geology—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by brewingeo** [comment]
Hi again, just one more comment. I did indeed see that any user can edit map points and while that might serve a good public function, it might not be best for maintaining good maps.  It takes work to find and prepare maps to upload into MapWarper and then rectify them.  And for someone, even an inexperienced user to perhaps mess up a nice rectified map is questionable. Maybe it’s best for users who favorite a map can alter their version of it, to be saved under a different name?  And perhaps the original map “owner” is notified that someone has alter their copy so that the original author can favorite their “improved “ version if desired.  I don’t know but it is the integrity of the, your, database of maps that is in jeopardy. Cheers, George Sent from Mail for Windows From: Tim WatersSent: Monday, July 4, 2022 5:56 AMTo: timwaters/mapwarperCc: brewingeo; AuthorSubject: Re: [timwaters/mapwarper] Disappearing Maps (Issue #217) Any user can edit and delete points from other maps, this might have happened Big Lake, although the database only shows there only being 1 control point added to this map.https://mapwarper.net/maps/64676#Show_tab Just add some more points and re-rectify it.Some maps might need to be re-rectified: e.g.Billings https://mapwarper.net/maps/34215#Preview_Rectified_Map_tab which should now be working.For the missing maps, only and admin or the person who uploaded them can delete them from the database.I found that a map had been uploaded with the title "Geologic map of the Deep Lake quadrangle, Park County, Wyoming" but that other user had deleted it.You can "favourite" a map from other users and it will appear in your list. But if the other user deletes them, it will go from your list.You could go through your activity list (see link top right "My activity") and see if a map had been deleted. But looking in the database, only 3 maps of yours was deleted in the past: probably when you were trying out different image formats, quality etc.Bridger Geology, USGS Geologic Map of Soda Springs Quad, Billings Geology—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
