### ISSUE TITLE
 Server is out of disk space. 

### ISSUE THREAD

**Issue by CharlesMaZ** [timwaters/mapwarper#222]
When i try upload map I get this error:

Server is out of disk space. Uploads have been disabled temporarily.

This server often runs out of disk space. Consider deleting your map after you have finished with it to help mapwarper.net to run for longer.

**Comment by dfurber** [comment]
MapWarper is hungry for disk space. Consider a larger server.

**Comment by timwaters** [comment]
yeah, I think this was about mapwarper.net which these issues also get some support about. 

Hopefully mapwarper.net will migrate to a larger server soon
