### ISSUE TITLE
clicking on "warp image" button on bottom of rectify tab doesn't rectify image

### ISSUE THREAD

**Issue by terrafrost** [timwaters/mapwarper#227]
In https://mapwarper.net/maps/67958#Rectify_tab , after I click on "Warp Image!" and see a "Map rectified." appear, I then click on the "Preview" tab and I get a "Whoops, the map needs to be recitifed before you can view it" message.

Any ideas?

**Comment by timwaters** [comment]
This is for mapwarper.net

Sorry the server got full up. I've disabled new uploads until it moves to a
new server but I've also freed up some space for rectification now.
