### ISSUE TITLE
How to create a mosaic

### ISSUE THREAD

**Issue by shang-jcu** [timwaters/mapwarper#255]
I've been trying to figure out how to create a mosaic in mapwarper.com. I couldn't find any tutorial or directions. This specific task is not mentioned in the programming historian lesson, either. The hints I found on the help page and on Git are too succinct for me to grasp. I tried cropping the images and then align them, but each time when I hit the align button, I was re-directed to rectify and would lose all the control points I put in earlier. Could anyone point me to the right direction? I'd appreciate it very much.

**Comment by timwaters** [comment]
u need to make a new mosaic and choose the maps to make it from (the maps in your favourites) https://mapwarper.net/layers/new
