### ISSUE TITLE
Unable to re-rectify map 46841

### ISSUE THREAD

**Issue by EdwardFinegan** [timwaters/mapwarper#259]
I have a map, 46841 that I assume was purged due to not logging in for a while. However when I try to re-rectify it, something doesn’t work. I don’t see any error messages but I’m still not able to export it. I also do not see the rectify action showing up in my activity tag.

**Comment by timwaters** [comment]
Hi,

thanks for the issue. Yes it got purged, sorry. I re-ran the rectification
but turned off the option to apply the mask and it looks ok now.
I think the bug is where its looking for a clipping mask to apply but that
is missing that so it fails.

**Comment by EdwardFinegan** [comment]
Thanks for the quick response, and an even bigger thanks for this website/service. Its really great!!!! Is there anyway to download the tiles so they can be hosted else where so they don't burden your server?

**Comment by timwaters** [comment]
tiles are not stored so cannot be downloaded. they are served dynamically
