### ISSUE TITLE
Problem with logiing via OSM

### ISSUE THREAD

**Issue by CharlesMaZ** [timwaters/mapwarper#276]
On mapwarper You can't login via OSM

**Comment by timwaters** [comment]
Might be because I changed password recently, will look into it, Thanks!

**Comment by timwaters** [comment]
Problem was server was trying and failing to resolve osm server via ipv6

solution was to edit  `/etc/gai.conf` and add this line:

```
precedence  2001:470::0/32   5
```
which forces it to use ipv4 and then restart apache

**Comment by timwaters** [comment]
many thanks! @CharlesMaZ for the report!
