### ISSUE TITLE
Please switch to OAuth 2.0 for OSM login

### ISSUE THREAD

**Issue by mmd-osm** [timwaters/mapwarper#277]
OAuth 1.0a will be sunset on osm.org in a few months, please switch to OAuth 2.0.

---

The OpenStreetMap operations team have taken the decision to retire OAuth 1.0a and HTTP Basic Auth support for the [www.openstreetmap.org](http://www.openstreetmap.org/) and API on the June 1st, 2024.
 
Apps that use OAuth 1.0a and HTTP Basic Auth will need to move to use OAuth 2.0
 
Full details and key dates are here:
https://community.openstreetmap.org/t/oauth-1-0a-and-http-basic-auth-shutdown/108490
 
Technical ticket:
https://github.com/openstreetmap/operations/issues/867
 
Social media:
https://en.osm.town/@openstreetmap/111821868082326620

Edit:
Added blog post: https://blog.openstreetmap.org/2024/04/17/oauth-1-0a-and-http-basic-auth-shutdown-on-openstreetmap-org/

**Comment by timwaters** [comment]
now live, seems to be working ok
