### ISSUE TITLE
Cannot Create Account

### ISSUE THREAD

**Issue by wrightkennedy** [timwaters/mapwarper#278]
When trying to create a new account, the site returns "We're sorry, but something went wrong. If you are the application owner check the logs for more information." Using an alternate method, such as GitHub, returns the error 'Could not authenticate you from GitHub because "Invalid credentials".'.

**Comment by memrekarakaya** [comment]
I have a problem like this too. I need to use this software in the article writing process. please help.

**Comment by timwaters** [comment]
should be fixed
