### ISSUE TITLE
Can't login with OSM account

### ISSUE THREAD

**Issue by benoit-dd** [timwaters/mapwarper#280]
Hi!

I'm unable to connect to https://www.mapwarper.net/u/sign_in with an OSM account, I asked on the french osm forum and other users have the same problem :https://forum.openstreetmap.fr/t/probleme-connexion-mapwarper-avec-compte-osm/25171/2

when I try, it opens a page with the following address: https://www.openstreetmap.org/oauth2/authorize?client_id=3j31OwH4ptOg2Wh_t8Uhcm01D3q9JNiccJ5g7vBAiUk&redirect_uri=https%3A%2F%2Fwww.mapwarper.net%2Fu%2Fauth%2Fosm_oauth2%2Fcallback&response_type=code&scope=read_prefs&state=f3240c0c5ec7e76ec36d9856ab1fab3d72541b241c66bab6

and the message (in french): "Une erreur s’est produite / L’URI de redirection n’est pas valide."

Not sure if linked with #276

**Comment by timwaters** [comment]
Hi,

I'm afk at the moment,

I wonder, could you try to log in via https://mapwarper.net instead of
https://www.mapwarper.net  ?
That should help me narrow things down.

Thanks!

**Comment by benoit-dd** [comment]
Yes, it works fine with https://mapwarper.net/ !

**Comment by timwaters** [comment]
Thank you for your help! I have been able to change the OAuth application on osm and added the www. subdomain so you should be able to use both now.
