### ISSUE TITLE
allow image download (original, unrectified)

### ISSUE THREAD

**Issue by fgnievinski** [timwaters/mapwarper#282]
it'd be nice to allow downloading the original unrectified image. sometimes one'd like to process the image for improved readability (e.g., increasing contrast, reducing color depth, removing background).

**Comment by timwaters** [comment]
This is possible in the software and is enabled on some mapwarper instances for other organisations but on mapwarper.net we disable it to save on disk space. Disks filling up is a major issue for the free instance. 

Thanks for the issue. I will give it the mapwarper.net label and close it.
