### ISSUE TITLE
unable to confirm email

### ISSUE THREAD

**Issue by oakton8** [timwaters/mapwarper#284]
When I attempt to confirm my email, I do not receive a confirmation email. I have double checked my spam folder and made sure I typed my address in correctly. I have also waited a little to see if it comes in, but it has not. What can I do?

**Comment by timwaters** [comment]
There is an issue with Gmail addresses. You can try another email from another provider, or email [ (see help page)](https://mapwarper.net/help) and I can manually activate.

Basically emails are being sent but Google is blocking them as the server isn't set up properly. It's a known issue on my list of things to do :)  I appreciate you taking the time to create this issue
