### ISSUE TITLE
“Mapbox Satellite” view is broken

### ISSUE THREAD

**Issue by reidpr** [timwaters/mapwarper#285]
Thanks for Map Warper.

The Mapbox Satellite view worked yesterday, but today it shows broken image icons instead of tiles. I’ve attached a screenshot.

![Screenshot 2024-10-01 at 6 41 50 PM](https://github.com/user-attachments/assets/1a3b4615-1b5a-4add-9efd-3fef86e0bf1a)

**Comment by timwaters** [comment]
Thanks for the issue. The layer is temporarily disabled as it went over free tier usage and started to cost lots.
