### ISSUE TITLE
landsat broken

### ISSUE THREAD

**Issue by timwaters** [timwaters/mapwarper#37]
telascience is broken, try another wms server

**Comment by drnickyoung** [comment]
any update on this? I have not had any luck on a mirror, is there a working solution?

**Comment by timwaters** [comment]
hmm, there is http://earthexplorer.usgs.gov/browse/landsat_8/2015/204/023/LC82040232015097LGN00.jpg

or we could find and put in a mapbox satellite layer...

**Comment by DaCor1** [comment]
Using the Mapbox layer would be fantastic and massively useful in areas
where OSM coverage is in its early stages (Africa, Middle East, parts of
Asia)

**Comment by drnickyoung** [comment]
A satellite layer would be fantastic. Am still finding my way around the code, afraid been some time since I played with Ruby. Will have a look, but yep satellite layer, mapbox, would be great.

**Comment by timwaters** [comment]
adding mapbox satellite tiles to master, will deploy soonish. closing in meantime!
