### ISSUE TITLE
when previewing map and you tick the layer is doen't work as it is generating wrong url

### ISSUE THREAD

**Issue by DaCor1** [timwaters/mapwarper#59]
when previewing map and you tick the layer is doen't work as it is generating wrong url

eg instead of http://mapwarper.net/layers/wms/101?FORMAT..... (101 is the layer)

it is trying http://mapwarper.net/layers/wms/1826/101?FORMAT (1826 is the map)

http://mapwarper.net/maps/1826#Preview_Map_tab

**Comment by IrlJidel** [comment]
Could you also hotpatch on the Rectify tab as well? 

Useful when you are trying to get it to seam better with adjacent sheets in layer

**Comment by chrishelenius** [comment]
Any updates? Rectify-tab still has this.

**Comment by timwaters** [comment]
Fixed in ruby1.9.1 branch and on the server
