### ISSUE TITLE
disable pdf upload

### ISSUE THREAD

**Issue by timwaters** [timwaters/mapwarper#63]
stop users trying to upload pdfs and it just confuses them

**Comment by timwaters** [comment]
new paperclip only allows images

**Comment by allthesignals** [comment]
Curious about reopening this, if possible - the only trouble is PDFs with multiple pages. I think users would want to see each page come in as a separate map. Do you remember the issues you ran into with this (aside from Paperclip limitations)?

**Comment by timwaters** [comment]
This was disabled as the main thing is that PDFs are an encapsulation format, they can have pages of text, vector graphics and raster graphics. Some users were trying to upload PDFs with vectors and rasters, paperclip was making a thumbnail, but the warper wasn't getting the image.  The main users for mapwarper.net are individuals, and it's easier to say "use an actual image format" :)

Feel free to create a new issue to support images in PDFs though - as I know there are organisations that rely on the format.  Multi page is an associated issue with it.

**Comment by allthesignals** [comment]
Gotcha, thanks - I have a large S3-type [bucket](https://nycdcp-dcm-alteration-maps.nyc3.digitaloceanspaces.com/) of PDF map _scans_ that will probably be easier to batch convert elsewhere instead of changing Map Warper :) thanks for the insight.

**Comment by timwaters** [comment]
You could adapt the import functionality to handle the conversion and import (for your own branch) if you wanted to keep the batch conversion process in the code. One very small advantage is that its possible to see what maps were imported for a given import process
