### ISSUE TITLE
Error runing mapwarper,REXML::ParseException in HomeController#index

### ISSUE THREAD

**Issue by AhmedLadhar** [timwaters/mapwarper#69]
Hi,
Got this error , after I try to run my local version of mapwarper with "rails s" :
#<REXML::ParseException: Missing end tag for 'hr' (got "body") Line: 6 Position: 169 Last 80 unconsumed characters: > /usr/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:335:in `pull_event' 

I am using ubuntu 14.04 and I guess that i have problems with my gems 's version . Here is a list of my local gems : 
 *** LOCAL GEMS ***

actionmailer (4.2.0, 4.1.5, 2.3.5)
actionpack (4.2.0, 4.1.5, 4.0.2, 2.3.5)
actionview (4.2.0, 4.1.5)
activejob (4.2.0)
activemodel (4.2.0, 4.1.5)
activerecord (4.2.0, 4.1.5, 2.3.5)
activerecord-postgis-adapter (2.2.0)
activeresource (2.3.5)
activesupport (4.2.0, 4.1.5, 4.0.2, 2.3.5)
acts-as-taggable-on (3.3.0)
acts_as_commentable (4.0.1)
arel (6.0.0, 5.0.1.20140414130214)
atomic (1.1.16)
bcrypt (3.1.7)
blankslate (2.1.2.4)
builder (3.2.2)
bundler (1.3.5)
capistrano (3.2.1)
capistrano-bundler (1.1.3)
capistrano-rails (1.1.1)
celluloid (0.15.2)
childprocess (0.3.9)
climate_control (0.0.3)
cocaine (0.5.4)
coffee-rails (4.0.1)
coffee-script (2.3.0)
coffee-script-source (1.7.1)
colorize (0.7.3)
daemon_controller (1.2.0)
daemons (1.1.9)
devise (3.3.0)
devise-encryptable (0.2.0)
erubis (2.7.0)
eventmachine (1.0.3)
execjs (2.2.1)
faraday (0.9.0)
fastercsv (1.5.5)
ffi (1.9.3)
gdal (0.0.5)
geoplanet (0.2.7)
georuby (2.2.1, 2.0.0)
globalid (0.3.3)
hashie (3.2.0)
hike (1.2.3)
hpricot (0.8.6)
i18n (0.7.0, 0.6.11, 0.6.9)
jbuilder (2.1.3)
jquery-rails (3.1.1)
jquery-ui-rails (3.0.1)
json (1.8.1, 1.8.0)
jwt (1.0.0)
kgio (2.9.2)
listen (2.7.9)
log4r (1.1.10)
loofah (2.0.1)
mail (2.5.4)
mime-types (1.25.1)
mini_portile (0.6.2)
minitest (5.4.0, 5.2.1)
multi_json (1.10.1, 1.8.0)
multi_xml (0.5.5)
multipart-post (2.0.0)
net-http-persistent (2.9)
net-scp (1.2.1, 1.1.1)
net-ssh (2.9.1, 2.6.8)
netrc (0.7.7)
nokogiri (1.6.6.2, 1.5.9)
oauth (0.4.7)
oauth2 (1.0.0)
oj (2.5.3)
omniauth (1.2.2)
omniauth-github (1.1.2)
omniauth-mediawiki (0.0.2)
omniauth-oauth (1.0.1)
omniauth-oauth2 (1.2.0)
omniauth-osm (0.3.2)
omniauth-twitter (1.0.1)
orm_adapter (0.5.0)
paperclip (4.2.0)
passenger (4.0.3)
pg (0.17.1, 0.15.1)
polyglot (0.3.5)
rack (1.6.0, 1.5.2, 1.0.1)
rack-protection (1.5.3)
rack-ssl (1.3.2)
rack-test (0.6.2)
rails (4.1.5)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.5)
rails-html-sanitizer (1.0.1)
rails-observers (0.1.2)
railties (4.2.0, 4.1.5, 4.0.2)
raindrops (0.13.0)
rake (10.3.2, 10.0.4)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rdoc (4.1.1, 3.9.4)
rdoc-data (4.0.1)
rerun (0.10.0)
rest-client (1.7.2)
rgeo (0.3.20)
rgeo-activerecord (1.1.0)
rvm1-capistrano3 (1.2.6)
sass (3.2.19)
sass-rails (4.0.3)
sdoc (0.4.1)
sinatra (1.3.2)
spawnling (2.1.5)
spring (1.1.3)
sprockets (2.11.0)
sprockets-rails (2.1.3)
sshkit (1.5.1)
thin (1.6.2)
thor (0.19.1, 0.18.1.20140116)
thread_safe (0.3.4, 0.1.3)
tilt (1.4.1)
timers (1.1.0)
treetop (1.4.15)
tzinfo (1.2.2, 1.1.0)
uglifier (2.5.3)
unicorn (4.8.3)
vagrant (1.4.3)
warden (1.2.3)
will_paginate (3.0.7)
yahoo-geoplanet (0.2.1)
yajl-ruby (1.2.0)
yql (0.0.2)

Ps: I get a previous error saying that I should run "rake db:migrate" and I run it

**Comment by timwaters** [comment]
sounds like it's related to #67 "FeedParser RSS feed broken due to 301 response from wordpress.com. Needs to support https"

**Comment by AhmedLadhar** [comment]
First of all ,I want to thank you for your quick response . 
I m not familiar with mapwarper and I looked to  #67  but I didn't get what I should do exactly . 
I try to connect to the server with https:localhost:3000 but I get an authentification error.

**Comment by AhmedLadhar** [comment]
First of all , I want to thank you for your quick response.
Finaly I tweak the problem by replacing "http://thinkwhere.wordpress.com/tag/mapwarper/feed/" with a http rss feed in app/controllers/home_controller.rb  . Please keep me updated if you could make the WordPress feed work correctly.
