### ISSUE TITLE
map upload metadata input is not wokring

### ISSUE THREAD

**Issue by solebox** [timwaters/mapwarper#78]
when adding metadata to the map in addition to the map name rails spits out an error 
the request:
{"utf8"=>"✓",
 "authenticity_token"=>"lGIV2kLpiG56cECzC8gNX5HTQoHtJPOcCG4iYWls4eh0fsrHfuq2OlMVMTU4yMdIm0v7PIFuUJDdidOxQxKtiw==",
 "map"=>{"title"=>"aaa",
 "description"=>"aaa",
 "tag_list"=>"aaa",
 "map_type"=>"is_map",
 "subject_area"=>"aaa",
 "unique_id"=>"aaa",
 "source_uri"=>"aaa",
 "call_number"=>"aaa",
 "publisher"=>"aaa",
 "publication_place"=>"aaa",
 "authors"=>"aaa",
 "date_depicted"=>"",
 "published_date(3i)"=>"18",
 "published_date(2i)"=>"4",
 "published_date(1i)"=>"1634",
 "reprint_date(3i)"=>"18",
 "reprint_date(2i)"=>"8",
 "reprint_date(1i)"=>"1818",
 "scale"=>"",
 "metadata_projection"=>"",
 "metadata_lat"=>"",
 "metadata_lon"=>"",
 "upload"=>#<ActionDispatch::Http::UploadedFile:0x00000006c052f0 @tempfile=#<File:/tmp/RackMultipart20151120-2372-14dv9fc.png>,
 @original_filename="modiin.png",
 @content_type="image/png",
 @headers="Content-Disposition: form-data; name=\"map[upload]\"; filename=\"modiin.png\"\r\nContent-Type: image/png\r\n">,
 "upload_url"=>""},
 "commit"=>"Create"}

The Error:
can't modify frozen ActiveSupport::HashWithIndifferentAccess

```
 def create
   @map = Map.new(map_params) <-

   if user_signed_in?
     @map.owner = current_user
```

**Comment by timwaters** [comment]
closing this due to new API and age
