### ISSUE TITLE
add map reset function?

### ISSUE THREAD

**Issue by lklepner** [timwaters/mapwarper#84]
I've run into an issue with one of the nypl maps where rectifying fails every time -
http://maps.nypl.org/warper/maps/26776

I wonder if there is a valid use case for having a map reset function if things get into a bad state?

**Comment by timwaters** [comment]
What do you mean by "reset"? A user can delete points and start again if need be.

**Comment by lklepner** [comment]
Something about this map is preventing it from being rectified. When I clicked rectify the prompt appears but nothing happens and then the map is locked. I've wondered if a setting has gotten into a bad state and needs to be cleared. I'll try wiping out the control points and re-adding

http://maps.nypl.org/warper/maps/26776

**Comment by timwaters** [comment]
okay, in the meantime, https://github.com/nypl-spacetime/nypl-warper may be the place for NYPL Warper specific issues. mapwarper is one for the core / shared codebase.

**Comment by lklepner** [comment]
ahh thanks. I'll enter the issue there.
