### ISSUE TITLE
Import multiple maps from CSV

### ISSUE THREAD

**Issue by samwilson** [timwaters/mapwarper#87]
It would be terrific to be able to import multiple maps, from external URLs, by uploading a CSV file. Has anyone done anything like this?

**Comment by timwaters** [comment]
Nice idea. There are batch imports for instances of the mapwarper on some institutions servers.  There is a simple "import from directory" import feature but its not used on mapwarper.net. Mapwarper.net is generally for individuals. 

For example there is the ability to batch import a Category/group of maps on the Wikimedia Commons Wikimaps Warper.

**Comment by samwilson** [comment]
Oh cool, thanks for the pointers. Especially re the Commons system. Will investigate further!
