### ISSUE TITLE
/maps doesn't work with Ubuntu 14.04

### ISSUE THREAD

**Issue by siru88** [timwaters/mapwarper#95]
I am trying to implement [mapwarper ](https://github.com/timwaters/mapwarper)for my server. The service is installed however mapscript doesn't seems to be working. I get the below error.

```
LoadError (cannot load such file -- mapscript):
  app/controllers/maps_controller.rb:692:in `<class:MapsController>'
  app/controllers/maps_controller.rb:1:in `<top (required)>'
```

I have installed ruby_mapscript and also added the below line in mapwarper/lib/enum_fu/Rakefile file. However, I still get the same error.

`  t.libs << '/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.0.0'`

Attached is the screenshot of the error in the browser when accessing http://<serverIP:3000/maps>

![mapscript error](https://cloud.githubusercontent.com/assets/12696196/16608341/5a669c14-4368-11e6-9086-5facc5798656.JPG)

Any help would be greatly appreciated.

**Comment by timwaters** [comment]
have a look in the provision script for vagrant which uses Trusty

https://github.com/timwaters/mapwarper/blob/master/lib/vagrant/provision.sh

Then try to load in the mapscript library in irb or something. 

if you are using rvm you may need to copy the mapscript.so library to a location where rvm can pick it up.

**Comment by siru88** [comment]
Thanks for responding Tim,

Following the .sh file gives me the following error.

```
make
compiling osr.cpp

osr.cpp: In function ‘OGRErr OSRSpatialReferenceShadow_ImportFromOzi(OSRSpatialReferenceShadow*, const char*, const char*, const char*)’:
osr.cpp:2476:59: error: cannot convert ‘const char*’ to ‘const char* const*’ for argument ‘2’ to ‘OGRErr OSRImportFromOzi(OGRSpatialReferenceH, const char* const*)’
     return OSRImportFromOzi( self, datum, proj, projParms );
                                                           ^
osr.cpp: In function ‘VALUE _wrap_new_SpatialReference(int, VALUE*, VALUE)’:
osr.cpp:2830:15: warning: unused variable ‘kwnames’ [-Wunused-variable]
   const char *kwnames[] = {

```
![error](https://cloud.githubusercontent.com/assets/12696196/16616811/5c43c69e-439d-11e6-836a-320c3f6e93b0.JPG)

**Comment by siru88** [comment]
I have managed to fix it by following [this](https://github.com/sourcepole/ruby_mapscript/issues/3)

**Comment by KamataRyo** [comment]
For my case with rbenv,  a symbolic link to `mapscript.so` enables local ruby to load it.

```
/home/user/.rbenv/versions/2.2.1/lib/ruby/vendor_ruby/2.2.0/x86_64-linux/mapscript.so -> /usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.0.0/mapscript.so
```
