### ISSUE TITLE
QUESTION - Changing Base Map Layer

### ISSUE THREAD

**Issue by spatialsteve** [timwaters/mapwarper#96]
I am trying to adjust the base map used in mapwarper, is this the correct file to adjust so I can include my own xyz base layer to replace the current OSM layer?

https://github.com/timwaters/mapwarper/blob/2b896f13dd4270c6531b533eb2dd506f93d86b98/app/assets/javascripts/layers.js

If so, would anyone mind assisting me with working out the Openlayers2 code to achieve this?

**Comment by timwaters** [comment]
You might also be interested in the wikimaps_new branch where I've added a control for users to add a custom XYZ layer to the warp view
